### ISSUE TITLE
Something should be changed in Minggugong Campus

### ISSUE THREAD

**Issue by RyanSu98** [Yohoa/Login_In_Nuaa_Portal_with_Python_n_Curl_Capative_portal_login_Hack_nuaa_portal#2]
I just moved to Minggugong Campus from Jinagjun Road Campus. And I find the value of _from_ should changed to `003cc944be32e253866e243f60c20815`, and then the shell would work properly. Please update the shell, thank you!

**Comment by Yohoa** [comment]
Roger! Your advice will be accepted and added to the repository.

Another question has emerged, however, and is necessary to be clarified.
That is: is this modification of the content of *form *a cross-campus
update, or just a marker of the user indicating where the request from?
Curious about that.

**Comment by Yohoa** [comment]
@rvfu 嗨，請問 _from_ 的數值是否是僅僅在明故宮校區被更改為了`003cc944be32e253866e243f60c20815 `，或是全校都進行了改變呢？望核實，感謝！

Best wishes,
Yohoa

**Comment by RyanSu98** [comment]
经过确认，两个校区的确是不一样的。
明故宫校区是 `003cc944be32e253866e243f60c20815`
将军路校区是 `003cc944be32e25365428f2dd2adbbe2`

**Comment by Yohoa** [comment]
#5
