### ISSUE TITLE
本脚本已经失效

### ISSUE THREAD

**Issue by splendidmata** [Yohoa/Login_In_Nuaa_Portal_with_Python_n_Curl_Capative_portal_login_Hack_nuaa_portal#3]
我在mac上用curl执行了，发现无法连接
地点：明故宫校区，已更换对应的form
bogon:~ ruixinwu$ curl 'http://202.119.65.214/iPortal/action/doLogin.do'  -X POST  -H 'Content-Type: application/x-www-form-urlencoded'  -H 'Referer: http://202.119.65.214/iPortal/index.htm?from=003cc944be32e253866e243f60c20815&wlanuserfirsturl=http://www.ip.cn/'  -H 'Accept: application/json, text/javascript, */*; q=0.01'  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.70 Safari/537.36'  -H 'Origin: http://202.119.65.214'  -H 'X-Requested-With: XMLHttpRequest'  --data 'username={0117xxxxx}&password={xxxxxx}&saved=1&from=003cc944be32e253866e243f60c20815&domain=1'
回应是：{"status":1,"statusText":"","id":"0","num":"0","num2":"0","data":"{\"domain\":\"公网资源\",\"ip\":\"172.18.104.222\",\"loginTime\":\"\",\"saved\":0,\"status\":\"reject\",\"username\":\"{0117xxxxx}\"}","data2":"[]"}
【为保护隐私我隐藏了学号和密码】

**Comment by splendidwrx** [comment]
参考瑞辅大佬的脚本知道问题在哪了
